version: '2'
services:
    # UAA-Service configuration
    uaa-service:
        image: uaa-service
        external_links:
            - uaa-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/uaa?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SLEEP=15 # gives time for the database to boot before the application
        ports:
            - 8080:8080

    # MySQL-Configuration
    uaa-mysql:
        container_name: uaa-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/uaa/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=uaa
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
